variables:
  hVer: &h-ver "0.123.8"

version: 2.1

orbs:
  docker: circleci/docker@2.4
  hugo: circleci/hugo@1.3
  k8s: circleci/kubernetes@1.3
  notify: hubci/notify@0.1

workflows:
  build-n-test-wf:
    jobs:
      - hugo/build:
          version: *h-ver
          source: "src"
          html-proofer: false
          filters:
            branches:
              ignore: trunk
      - docker/publish:
          attach-at: "src"
          deploy: false
          registry: "ghcr.io"
          image: "eventhunt-org/launch-site"
          lint-dockerfile: true
          remote-docker-version: "20.10.24"
          tag: "$CIRCLE_SHA1,<< pipeline.git.branch >>,<< pipeline.number >>"
          requires:
            - hugo/build
          filters:
            branches:
              ignore: trunk
  build-n-deploy-wf:
    jobs:
      - hugo/build:
          version: *h-ver
          source: "src"
          html-proofer: false
          filters:
            branches:
              only: trunk
      - docker/publish:
          attach-at: "src"
          registry: "ghcr.io"
          image: "eventhunt-org/launch-site"
          remote-docker-version: "20.10.24"
          tag: "$CIRCLE_SHA1,<< pipeline.git.branch >>,<< pipeline.number >>,latest"
          requires:
            - hugo/build
          filters:
            branches:
              only: trunk
          context: ghcr-ctx
      - deploy:
          requires:
            - docker/publish
          filters:
            branches:
              only: trunk
          context:
            - k8s-ctx
            - notify-ctx

jobs:
  deploy:
    docker:
      - image: hubci/strawberry:0.21.0
    steps:
      - k8s/install-kubeconfig
      - k8s/install-kubectl:
          kubectl-version: "v1.28.6"
      - run:
          name: "Deploy Production"
          command: kubectl set image --namespace=melitix deployment/eventhunt-launch-site site=ghcr.io/eventhunt-org/launch-site:$CIRCLE_SHA1
      - notify/notify-mattermost:
          text: "EventHunt Launch Site (production) published. https://EventHunt.org"
